language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository

script: ./gradlew clean check test install
